/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/TitleText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SubtitleText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/InputField`; params?: Router.UnknownInputParams; } | { pathname: `/../@types/InputFieldProps`; params?: Router.UnknownInputParams; } | { pathname: `/../@types/TextComponentsProps`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/TitleText`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/SubtitleText`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/InputField`; params?: Router.UnknownOutputParams; } | { pathname: `/../@types/InputFieldProps`; params?: Router.UnknownOutputParams; } | { pathname: `/../@types/TextComponentsProps`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/TitleText${`?${string}` | `#${string}` | ''}` | `/../components/SubtitleText${`?${string}` | `#${string}` | ''}` | `/../components/InputField${`?${string}` | `#${string}` | ''}` | `/../@types/InputFieldProps${`?${string}` | `#${string}` | ''}` | `/../@types/TextComponentsProps${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/TitleText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SubtitleText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/InputField`; params?: Router.UnknownInputParams; } | { pathname: `/../@types/InputFieldProps`; params?: Router.UnknownInputParams; } | { pathname: `/../@types/TextComponentsProps`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; };
    }
  }
}
